language: deu

companys:
  Aldi:
    - aldi
  Bauhaus:
    - bauhaus
  Colruyt:
    - colruyt
  Delhaize:
    - delhaize
  Deutsche Post:
    - deutsche post
  Drogerie Markt:
    - drogerie

  Edeka:
   - edeka
  Getraenke:
    - Getraenke Tempel
  Kaiser's:
    - kaiser
  Kaufland:
    - kaufland
    - kauf land
  Kodi:
    - kodi
  Lidl:
    - lidl
  Marktkauf:
    - marktkauf
  Migros:
    - genossenschaft migros
  Netto Marken-Discount:
    - netto-online
    - Marken-Discount
    - Marken
    - Netto
    - netto
  Penny:
    - penny
    - p e n n y
    - m a r k t gmbh
  REWE:
    - rewe
  Real:
    - real
  SuperBioMarkt:
    - SuperBioMarkt
  Tanken:
    - shell
    - esso
    - aral
    - avia
    - tankstelle
    - zapfpunkt
    - zapfstelle
    - zapfsäule

# Sum keys roughly ordered by likelyhood.
sum_keys:
  - summe
  - gesamtbetrag
  - gesamt
  - total
  - sum
  - zwischensumme
  - te betalen
  - zu zahlen
  - SUHRE

formats:
  sum: '\d+(\.\s?|,\s?|[^a-zA-Z\d])\d{2}'

  # Matches dates like 19.08.15 and 19. 08. 2015
  date: '\b([0123]?\d\s?\.\s?[01]?\d\s?\.\s?(?:20)?\d\d)\b'

  postal_code: '\b(\d{5})\s+[a-z]'
