receipts_path: "data/txt"

markets:
  Penny:
    - penny

  REWE:
    - REWE

  Real:
    - real

  Netto:
    - netto-online
    - Marken-Discount
    - Marken-Discount
    - Netto
    - netto

  Kaiser's:
    - kaiser
    - kaiserswerther straße 270

  Aldi:
    - aldi
    - friedrichstr 128—133

  Lidl:
    - lidl

  Edeka:
    - edeka

  Drogerie:
    - drogerie

  Tanken:
    - shell
    - esso station
    - aral
    - total tankstelle
    - RK Tankstellen

sum_keys:
  - summe
  - SUMME
  - Sume
  - gesamtbetrag
  - gesamt
  - total
  - sum
  - SUMHE
  - bar

sum_format: '\d+(\.\s?|,\s?|[^a-zA-Z\d])\d{2}'
date_format: '(?P<date>(\d{2,4}(\.\s?|[^a-zA-Z\d])\d{2}(\.\s?|[^a-zA-Z\d])(19|20)?\d\d)\s+)'